# Generated by Django 4.2.23 on 2026-08-11 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0011_vehicle_average_speed_kph_vehicle_body_type_and_more"),
        ("iam", "0002_outboundmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "plan_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("horizon_hours", models.PositiveIntegerField(default=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready to solve"),
                            ("solving", "Solving"),
                            ("solved", "Solved"),
                            ("failed", "Failed"),
                            ("committed", "Committed"),
                            ("superseded", "Superseded by a re-plan"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "objective",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cost/service weight overrides for the solver",
                    ),
                ),
                (
                    "solver",
                    models.CharField(
                        choices=[
                            ("greedy", "Greedy (savings + local search)"),
                            ("ortools", "OR-Tools"),
                        ],
                        default="greedy",
                        max_length=10,
                    ),
                ),
                (
                    "solver_seconds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("solver_status", models.CharField(blank=True, max_length=40)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("committed_by", models.CharField(blank=True, max_length=150)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_plans",
                        to="iam.branch",
                    ),
                ),
                (
                    "parent_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replans",
                        to="dispatch.dispatchplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-plan_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("ftl", "Full truckload"),
                            ("multi_drop_leg", "Multi-drop leg"),
                            ("pickup_only", "Pickup only"),
                            ("delivery_only", "Delivery only"),
                            ("reposition", "Repositioning"),
                        ],
                        default="ftl",
                        max_length=20,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "volume_cbm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("packages", models.PositiveIntegerField(default=1)),
                (
                    "temperature_class",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("chiller", "Chiller"),
                            ("frozen", "Frozen"),
                        ],
                        default="dry",
                        max_length=10,
                    ),
                ),
                (
                    "temp_set_point_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("pickup_window_start", models.DateTimeField(blank=True, null=True)),
                ("pickup_window_end", models.DateTimeField(blank=True, null=True)),
                ("drop_window_start", models.DateTimeField(blank=True, null=True)),
                ("drop_window_end", models.DateTimeField(blank=True, null=True)),
                ("pickup_service_minutes", models.PositiveIntegerField(default=30)),
                ("drop_service_minutes", models.PositiveIntegerField(default=30)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("must_go", "Must go - cannot be outsourced away"),
                            ("normal", "Normal"),
                            ("deferrable", "Deferrable"),
                        ],
                        default="normal",
                        max_length=12,
                    ),
                ),
                ("allowed_vehicle_types", models.JSONField(blank=True, default=list)),
                ("banned_vehicles", models.JSONField(blank=True, default=list)),
                (
                    "revenue_estimate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "outsource_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What the spot market would charge to move this - the disjunction penalty",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("planned", "Planned"),
                            ("outsourced", "Outsourced"),
                            ("dropped", "Dropped"),
                            ("committed", "Committed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("drop_reason", models.CharField(blank=True, max_length=240)),
                (
                    "dropoff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_dropoffs",
                        to="fleet.place",
                    ),
                ),
                (
                    "indent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_tasks",
                        to="fleet.indent",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_tasks",
                        to="fleet.order",
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_pickups",
                        to="fleet.place",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="dispatch.dispatchplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="TravelMatrixEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("origin_key", models.CharField(max_length=60)),
                ("destination_key", models.CharField(max_length=60)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration_minutes",
                    models.DecimalField(decimal_places=1, max_digits=8),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("haversine", "Haversine estimate"),
                            ("osrm", "OSRM"),
                            ("google", "Google Distance Matrix"),
                            ("learned", "Learned from GPS traces"),
                        ],
                        default="haversine",
                        max_length=10,
                    ),
                ),
                ("vehicle_class", models.CharField(blank=True, max_length=20)),
                (
                    "time_bucket",
                    models.CharField(
                        blank=True,
                        help_text="Hour-of-day band, e.g. '08-10'",
                        max_length=10,
                    ),
                ),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("hit_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["origin_key", "destination_key"],
                        name="dispatch_tr_origin__ebc6c1_idx",
                    )
                ],
                "unique_together": {
                    (
                        "origin_key",
                        "destination_key",
                        "provider",
                        "vehicle_class",
                        "time_bucket",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="PlanVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("own", "Own"),
                            ("attached", "Attached"),
                            ("leased", "Leased"),
                            ("hired", "Hired (terms known)"),
                            ("spot_slot", "Spot capacity slot"),
                        ],
                        default="own",
                        max_length=12,
                    ),
                ),
                (
                    "start_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "start_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("position_stale", models.BooleanField(default=False)),
                (
                    "available_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "capacity_cbm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "temperature_class",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("chiller", "Chiller"),
                            ("frozen", "Frozen"),
                            ("multi", "Multi"),
                        ],
                        default="dry",
                        max_length=10,
                    ),
                ),
                (
                    "cost_per_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_per_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fixed_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_stops", models.PositiveIntegerField(default=20)),
                ("max_route_km", models.PositiveIntegerField(default=800)),
                ("max_duty_minutes", models.PositiveIntegerField(default=600)),
                ("locked_to_route", models.BooleanField(default=False)),
                ("excluded", models.BooleanField(default=False)),
                ("exclusion_reason", models.CharField(blank=True, max_length=240)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_vehicles",
                        to="fleet.driver",
                    ),
                ),
                (
                    "must_return_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_vehicle_returns",
                        to="fleet.place",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_vehicles",
                        to="dispatch.dispatchplan",
                    ),
                ),
                (
                    "start_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_vehicle_starts",
                        to="fleet.place",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_vehicles",
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_vehicles",
                        to="fleet.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlannedRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_duration_minutes", models.PositiveIntegerField(default=0)),
                ("drive_minutes", models.PositiveIntegerField(default=0)),
                ("wait_minutes", models.PositiveIntegerField(default=0)),
                (
                    "dead_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_load_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "utilisation_weight_percent",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "utilisation_volume_percent",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimated_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("temperature_class", models.CharField(default="dry", max_length=10)),
                ("feasible", models.BooleanField(default=True)),
                ("violations", models.JSONField(blank=True, default=list)),
                ("locked", models.BooleanField(default=False)),
                (
                    "committed_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_routes",
                        to="fleet.trip",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="dispatch.dispatchplan",
                    ),
                ),
                (
                    "plan_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="dispatch.planvehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PlanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("collected", "Demand collected"),
                            ("solved", "Solved"),
                            ("task_dropped", "Task dropped"),
                            ("manual_move", "Manual move"),
                            ("hire_requested", "Hire requested"),
                            ("quote_accepted", "Quote accepted"),
                            ("committed", "Committed"),
                            ("route_committed", "Route committed"),
                            ("replanned", "Re-planned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("actor", models.CharField(blank=True, max_length=150)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="dispatch.dispatchplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HireRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=60)),
                (
                    "temperature_class",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("chiller", "Chiller"),
                            ("frozen", "Frozen"),
                        ],
                        default="dry",
                        max_length=10,
                    ),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("report_by", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("quoted", "Quoted"),
                            ("awarded", "Awarded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "awarded_hire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hire_requirement",
                        to="fleet.vehiclehire",
                    ),
                ),
                (
                    "dropoff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hire_requirement_dropoffs",
                        to="fleet.place",
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hire_requirement_pickups",
                        to="fleet.place",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hire_requirements",
                        to="dispatch.dispatchplan",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hire_requirements",
                        to="dispatch.dispatchtask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlannedStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("drop", "Drop"),
                            ("rest", "Rest"),
                            ("return", "Return"),
                        ],
                        default="drop",
                        max_length=10,
                    ),
                ),
                ("planned_arrival", models.DateTimeField(blank=True, null=True)),
                ("planned_departure", models.DateTimeField(blank=True, null=True)),
                ("service_minutes", models.PositiveIntegerField(default=0)),
                ("wait_minutes", models.PositiveIntegerField(default=0)),
                (
                    "load_after_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "load_after_cbm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "distance_from_previous_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("locked", models.BooleanField(default=False)),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("actual_departure", models.DateTimeField(blank=True, null=True)),
                ("variance_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_stops",
                        to="fleet.place",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="dispatch.plannedroute",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stops",
                        to="dispatch.dispatchtask",
                    ),
                ),
            ],
            options={
                "ordering": ["route_id", "sequence"],
                "unique_together": {("route", "sequence")},
            },
        ),
        migrations.AddIndex(
            model_name="dispatchtask",
            index=models.Index(
                fields=["plan", "status"], name="dispatch_di_plan_id_71ffda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchplan",
            index=models.Index(
                fields=["status", "-plan_date"], name="dispatch_di_status_782785_idx"
            ),
        ),
    ]
