# Generated by Django 4.2.23 on 2026-08-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0011_vehicle_average_speed_kph_vehicle_body_type_and_more"),
        ("dispatch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrierOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offered_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("rate_basis", models.CharField(default="trip", max_length=10)),
                ("vehicle_number", models.CharField(blank=True, max_length=20)),
                ("vehicle_type", models.CharField(blank=True, max_length=60)),
                (
                    "temperature_class",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("chiller", "Chiller"),
                            ("frozen", "Frozen"),
                        ],
                        default="dry",
                        max_length=10,
                    ),
                ),
                ("gps_available", models.BooleanField(default=False)),
                ("driver_name", models.CharField(blank=True, max_length=120)),
                ("driver_phone", models.CharField(blank=True, max_length=20)),
                (
                    "message_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="iam.OutboundMessage this RFQ was sent as",
                        null=True,
                    ),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="invited",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=240)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="dispatch.hirerequirement",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrier_offers",
                        to="fleet.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["offered_rate", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requirement", "status"],
                        name="dispatch_ca_require_6610a2_idx",
                    )
                ],
            },
        ),
    ]
