# Generated by Django 4.2.23 on 2026-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0002_carrieroffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchplan",
            name="collection_filters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="What universe of demand `collect` pulled in - customers, places, temperature class, a date window or explicit order ids",
            ),
        ),
    ]
