# Generated by Django 4.2.23 on 2026-08-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0003_dispatchplan_collection_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedroute",
            name="utilisation_volume_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Null when the vehicle's volume capacity was never recorded, not 0",
                max_digits=5,
                null=True,
            ),
        ),
    ]
