# Generated by Django 4.2.23 on 2026-08-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0012_indent_priority_indent_temp_set_point_c_and_more"),
        ("dispatch", "0004_alter_plannedroute_utilisation_volume_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchplan",
            name="is_scenario",
            field=models.BooleanField(
                default=False,
                help_text="A what-if child plan from `compare` - not shown as a first-class plan until `adopt` transplants its routes onto the parent",
            ),
        ),
        migrations.AddField(
            model_name="dispatchtask",
            name="pinned_vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="A dispatcher-forced vehicle for this task - honoured by the next solve instead of the solver's own choice (docs/DISPATCH-PLANNER-V2.md §8.1)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_dispatch_tasks",
                to="fleet.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="planevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("collected", "Demand collected"),
                    ("solved", "Solved"),
                    ("task_dropped", "Task dropped"),
                    ("manual_move", "Manual move"),
                    ("hire_requested", "Hire requested"),
                    ("quote_accepted", "Quote accepted"),
                    ("committed", "Committed"),
                    ("route_committed", "Route committed"),
                    ("replanned", "Re-planned"),
                    ("scenario_compared", "Scenario compared"),
                    ("scenario_adopted", "Scenario adopted"),
                ],
                max_length=20,
            ),
        ),
    ]
