# Generated by Django 4.2.23 on 2026-08-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dispatch",
            "0005_dispatchplan_is_scenario_dispatchtask_pinned_vehicle_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchtask",
            name="outsource_confidence",
            field=models.CharField(
                choices=[
                    ("contract", "Vendor contract rate"),
                    ("lane", "This lane's own history"),
                    ("corridor", "Corridor history (state to state)"),
                    ("type", "Vendor's vehicle-type average"),
                    ("fallback", "National fallback - no history"),
                ],
                default="fallback",
                help_text="How grounded outsource_estimate is - see solver.costing.spot_rate_for_lane",
                max_length=10,
            ),
        ),
    ]
