# Generated by Django 4.2.23 on 2026-08-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0006_dispatchtask_outsource_confidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("planned", "Planned"),
                    ("outsourced", "Outsourced"),
                    ("dropped", "Dropped"),
                    ("deferred", "Deferred to the next plan"),
                    ("held_for_review", "Held for manual review"),
                    ("committed", "Committed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ScenarioProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("milk_run", "Milk run - multi-drop consolidation"),
                            ("long_haul", "Long haul"),
                            ("reefer", "Reefer - temperature controlled"),
                            ("local_delivery", "Local delivery"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower matches first when more than one profile could apply",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "match_temperature_classes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["chiller","frozen"] - empty matches any temperature',
                    ),
                ),
                (
                    "match_min_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "match_max_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "match_min_drops",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum stops sharing one pickup",
                        null=True,
                    ),
                ),
                (
                    "match_same_city_only",
                    models.BooleanField(
                        default=False,
                        help_text="Only match when pickup and every drop share a city",
                    ),
                ),
                (
                    "base_strategy",
                    models.CharField(
                        default="balanced",
                        help_text="A preset name from solver.strategies.STRATEGY_PRESETS",
                        max_length=20,
                    ),
                ),
                ("weight_overrides", models.JSONField(blank=True, default=dict)),
                ("constraint_overrides", models.JSONField(blank=True, default=dict)),
                (
                    "fallback_action",
                    models.CharField(
                        choices=[
                            ("outsource", "Buy on the spot market"),
                            (
                                "relax",
                                "Retry once under the fallback profile's own logic",
                            ),
                            ("defer", "Defer to the next plan"),
                            ("hold", "Hold for manual dispatcher review"),
                        ],
                        default="outsource",
                        max_length=10,
                    ),
                ),
                (
                    "fallback_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text='Only used when fallback_action is "relax" - the profile to retry under',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dispatch.scenarioprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="dispatchtask",
            name="matched_scenario",
            field=models.ForeignKey(
                blank=True,
                help_text="Which scenario profile shaped this task's planning logic, if any - set by the solver, see solver.scenarios",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_tasks",
                to="dispatch.scenarioprofile",
            ),
        ),
    ]
