# Generated by Django 4.2.23 on 2026-08-04 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("fleet", "0003_indent_order_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_bank", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Positive on the account's natural side",
                        max_digits=16,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CostCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "centre_type",
                    models.CharField(
                        choices=[
                            ("vehicle", "Vehicle"),
                            ("branch", "Branch"),
                            ("route", "Route"),
                            ("driver", "Driver"),
                            ("other", "Other"),
                        ],
                        default="vehicle",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_centres",
                        to="iam.branch",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_centres",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 2026-27", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "entry_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("narration", models.CharField(blank=True, max_length=240)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual journal"),
                            ("invoice", "Customer invoice"),
                            ("bill", "Vendor bill"),
                            ("receipt", "Customer receipt"),
                            ("payment", "Vendor/driver payment"),
                            ("expense", "Trip expense"),
                            ("fuel", "Fuel purchase"),
                            ("settlement", "Driver settlement"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, max_length=40)),
                ("reference_id", models.CharField(blank=True, max_length=40)),
                ("is_posted", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="iam.branch",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="accounting.fiscalyear",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverses",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "journal entries",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("payment", "Payment"), ("receipt", "Receipt")],
                        default="payment",
                        max_length=10,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("neft", "NEFT"),
                            ("rtgs", "RTGS"),
                            ("imps", "IMPS"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                            ("fastag", "FASTag wallet"),
                        ],
                        default="neft",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="UTR, cheque or transaction reference",
                        max_length=60,
                    ),
                ),
                ("narration", models.CharField(blank=True, max_length=240)),
                ("status", models.CharField(default="recorded", max_length=20)),
                (
                    "bank_account",
                    models.ForeignKey(
                        help_text="Bank or cash account the money moved through",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounting.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="iam.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="fleet.customer",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="fleet.driver",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="fleet.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40, unique=True)),
                (
                    "bill_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tds_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("narration", models.CharField(blank=True, max_length=240)),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bills",
                        to="iam.branch",
                    ),
                ),
                (
                    "cost_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bills",
                        to="accounting.costcentre",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="accounting.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bills",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="fleet.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="accounting.vendorbill",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="fleet.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="accounting.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["payment_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "cost_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        to="accounting.costcentre",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["entry_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["account"], name="accounting__account_c6b1e8_idx"
                    ),
                    models.Index(
                        fields=["cost_centre"], name="accounting__cost_ce_403c06_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["-entry_date"], name="accounting__entry_d_c83b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="accounting__referen_4bf694_idx",
            ),
        ),
    ]
