# Generated by Django 4.2.23 on 2026-08-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0009_vehiclehire"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorbill",
            name="hire",
            field=models.ForeignKey(
                blank=True,
                help_text="The outside-sourced trip this bill settles, when it is a freight hire",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="fleet.vehiclehire",
            ),
        ),
    ]
