# Generated by Django 4.2.23 on 2026-08-04 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("manager", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=24, unique=True),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("ftl", "Full truck load"),
                            ("ptl", "Part truck load"),
                            ("parcel", "Parcel"),
                            ("rental", "Vehicle rental"),
                            ("reverse", "Reverse pickup"),
                        ],
                        default="ftl",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("payload_description", models.CharField(blank=True, max_length=240)),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "volume_cbm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("packages", models.PositiveIntegerField(default=1)),
                (
                    "declared_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "freight_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cod_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("to_pay", "To pay"),
                            ("paid", "Paid"),
                            ("tbb", "To be billed"),
                            ("cod", "Cash on delivery"),
                        ],
                        default="to_pay",
                        max_length=20,
                    ),
                ),
                ("eway_bill_number", models.CharField(blank=True, max_length=30)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("pod_required", models.BooleanField(default=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("status", models.CharField(default="created", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="fleet.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "Warehouse"),
                            ("hub", "Branch / hub"),
                            ("customer", "Customer site"),
                            ("plant", "Plant"),
                            ("fuel_station", "Fuel station"),
                            ("toll_plaza", "Toll plaza"),
                            ("workshop", "Workshop"),
                            ("parking", "Truck parking"),
                            ("checkpost", "RTO check post"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("landmark", models.CharField(blank=True, max_length=180)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("pincode", models.CharField(blank=True, max_length=6)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "loading_hours",
                    models.CharField(
                        blank=True, help_text="e.g. 09:00-18:00", max_length=60
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="fleet.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "states",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated Indian states covered",
                        max_length=240,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "boundary",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional [[lat, lng], ...] outline",
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("transporter", "Attached transporter"),
                            ("broker", "Broker / commission agent"),
                            ("workshop", "Workshop"),
                            ("fuel", "Fuel station"),
                            ("tyre", "Tyre vendor"),
                            ("insurance", "Insurance"),
                            ("other", "Other"),
                        ],
                        default="transporter",
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("msme_number", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("bank_account", models.CharField(blank=True, max_length=30)),
                ("ifsc", models.CharField(blank=True, max_length=15)),
                ("payment_terms_days", models.PositiveIntegerField(default=30)),
                (
                    "tds_percent",
                    models.DecimalField(decimal_places=2, default=2, max_digits=5),
                ),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="driver",
            name="daily_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="driver",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="home_city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="driver",
            name="monthly_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_odometer_km",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="engine_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fastag_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(default="diesel", max_length=20),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="make_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("waypoint_type", models.CharField(default="drop", max_length=20)),
                ("planned_arrival", models.DateTimeField(blank=True, null=True)),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="fleet.order",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waypoints",
                        to="fleet.place",
                    ),
                ),
            ],
            options={
                "ordering": ["order_id", "sequence"],
                "unique_together": {("order", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="TripExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("toll", "Toll / FASTag"),
                            ("driver_allowance", "Driver bhatta"),
                            ("loading", "Loading"),
                            ("unloading", "Unloading"),
                            ("rto_fine", "RTO fine"),
                            ("police", "Police / checkpost"),
                            ("parking", "Parking"),
                            ("repair", "On-road repair"),
                            ("permit", "Permit / border tax"),
                            ("halting", "Halting charges"),
                            ("other", "Other"),
                        ],
                        default="toll",
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expense_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("paid_by", models.CharField(default="driver", max_length=20)),
                ("receipt_number", models.CharField(blank=True, max_length=40)),
                ("remarks", models.CharField(blank=True, max_length=240)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="fleet.driver",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="fleet.order",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="fleet.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="fleet.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrackingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=40)),
                ("code", models.CharField(max_length=40)),
                ("details", models.CharField(blank=True, max_length=240)),
                ("city", models.CharField(blank=True, max_length=80)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="fleet.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=60)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("per_km", "Per km"),
                            ("per_ton_km", "Per ton per km"),
                            ("per_kg", "Per kg"),
                            ("per_trip", "Fixed per trip"),
                            ("per_hour", "Per hour"),
                        ],
                        default="per_km",
                        max_length=20,
                    ),
                ),
                (
                    "base_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_kg_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_ton_km_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_hour_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "minimum_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "loading_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unloading_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "halting_charge_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fuel_surcharge_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="5% GTA without ITC, 12% with ITC",
                        max_digits=5,
                    ),
                ),
                (
                    "reverse_charge",
                    models.BooleanField(
                        default=False, help_text="GST payable by consignee under RCM"
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_rates",
                        to="fleet.customer",
                    ),
                ),
                (
                    "service_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_rates",
                        to="fleet.servicearea",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, unique=True)),
                ("origin", models.CharField(max_length=120)),
                ("destination", models.CharField(max_length=120)),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_quotes",
                        to="fleet.customer",
                    ),
                ),
                (
                    "service_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="fleet.servicerate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proof_type", models.CharField(default="signature", max_length=20)),
                ("receiver_name", models.CharField(blank=True, max_length=120)),
                ("receiver_phone", models.CharField(blank=True, max_length=20)),
                ("remarks", models.CharField(blank=True, max_length=240)),
                ("file_url", models.URLField(blank=True)),
                ("otp", models.CharField(blank=True, max_length=6)),
                ("otp_verified", models.BooleanField(default=False)),
                (
                    "shortage_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("damage_reported", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="fleet.order",
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proofs",
                        to="fleet.waypoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.AddField(
            model_name="place",
            name="service_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="fleet.servicearea",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dropoff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dropoff_orders",
                to="fleet.place",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fleet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fleet.fleet",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="lorry_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fleet.lorryreceipt",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pickup_orders",
                to="fleet.place",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fleet.servicerate",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fleet.trip",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fleet.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fleet.vendor",
            ),
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.CharField(max_length=180)),
                ("interval_km", models.PositiveIntegerField(default=0)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("last_service_km", models.PositiveIntegerField(default=0)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("next_due_km", models.PositiveIntegerField(default=0)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_schedules",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle__registration_number", "task"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("breakdown", "Breakdown"),
                            ("accident", "Accident"),
                            ("tyre", "Tyre"),
                            ("documents", "Documents"),
                            ("delay", "Delay"),
                            ("route", "Route deviation"),
                            ("safety", "Safety"),
                            ("fuel_theft", "Fuel pilferage"),
                            ("other", "Other"),
                        ],
                        default="breakdown",
                        max_length=20,
                    ),
                ),
                ("priority", models.CharField(default="medium", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("location_text", models.CharField(blank=True, max_length=180)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("assigned_to", models.CharField(blank=True, max_length=120)),
                ("resolution", models.CharField(blank=True, max_length=240)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="open", max_length=20)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="fleet.driver",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="fleet.order",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="fleet.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FuelEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("station_name", models.CharField(blank=True, max_length=180)),
                (
                    "entry_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("odometer_km", models.PositiveIntegerField(default=0)),
                (
                    "volume_litres",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "rate_per_litre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("fastag", "FASTag"),
                            ("fuel_card", "Fuel card"),
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("credit", "Station credit"),
                        ],
                        default="fuel_card",
                        max_length=20,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=40)),
                (
                    "mileage_kmpl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("remarks", models.CharField(blank=True, max_length=240)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_entries",
                        to="fleet.driver",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_entries",
                        to="fleet.place",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_entries",
                        to="fleet.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_entries",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "fuel entries",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="fleet",
            name="drivers",
            field=models.ManyToManyField(
                blank=True, related_name="fleets", to="fleet.driver"
            ),
        ),
        migrations.AddField(
            model_name="fleet",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_fleets",
                to="fleet.fleet",
            ),
        ),
        migrations.AddField(
            model_name="fleet",
            name="service_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleets",
                to="fleet.servicearea",
            ),
        ),
        migrations.AddField(
            model_name="fleet",
            name="vehicles",
            field=models.ManyToManyField(
                blank=True, related_name="fleets", to="fleet.vehicle"
            ),
        ),
        migrations.AddField(
            model_name="fleet",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleets",
                to="fleet.vendor",
            ),
        ),
        migrations.CreateModel(
            name="ComplianceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("rc", "Registration certificate"),
                            ("insurance", "Insurance"),
                            ("fitness", "Fitness certificate"),
                            ("permit_national", "National permit"),
                            ("permit_state", "State permit"),
                            ("puc", "PUC certificate"),
                            ("road_tax", "Road tax"),
                            ("fastag", "FASTag KYC"),
                            ("gps_certificate", "GPS/VLT certificate"),
                            ("licence", "Driving licence"),
                            ("aadhaar", "Aadhaar"),
                            ("police_verification", "Police verification"),
                            ("medical", "Medical fitness"),
                        ],
                        default="insurance",
                        max_length=24,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=60)),
                ("issuing_authority", models.CharField(blank=True, max_length=140)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("reminder_days", models.PositiveIntegerField(default=30)),
                ("file_url", models.URLField(blank=True)),
                ("notes", models.CharField(blank=True, max_length=240)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery zone"),
                            ("pickup", "Pickup zone"),
                            ("hub", "Hub zone"),
                            ("restricted", "Restricted zone"),
                        ],
                        default="delivery",
                        max_length=20,
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "center_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "radius_km",
                    models.DecimalField(decimal_places=2, default=10, max_digits=7),
                ),
                ("colour", models.CharField(default="#0d5f45", max_length=9)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="fleet.servicearea",
                    ),
                ),
            ],
            options={
                "ordering": ["service_area__name", "name"],
                "unique_together": {("service_area", "name")},
            },
        ),
    ]
