# Generated by Django 4.2.23 on 2026-08-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
        ("fleet", "0002_fleetops"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, unique=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=60)),
                ("vehicles_required", models.PositiveIntegerField(default=1)),
                ("material", models.CharField(blank=True, max_length=180)),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("required_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("remarks", models.CharField(blank=True, max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("allocated", "Allocated"),
                            ("converted", "Converted to order"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="iam.branch",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="fleet_order_status_581200_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tracking_number"], name="fleet_order_trackin_fdbed6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["branch", "status"], name="fleet_order_branch__04e5b9_idx"
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indents",
                to="iam.branch",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indents",
                to="fleet.customer",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indents",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="dropoff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dropoff_indents",
                to="fleet.place",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indents",
                to="fleet.order",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="pickup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pickup_indents",
                to="fleet.place",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="service_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indents",
                to="fleet.servicerate",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indents",
                to="fleet.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="indent",
            index=models.Index(
                fields=["status", "-created_at"], name="fleet_inden_status_3523fc_idx"
            ),
        ),
    ]
