# Generated by Django 4.2.23 on 2026-08-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_indent_order_branch_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proofofdelivery",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "proofs of delivery",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="gst_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="The consignment this bills. Freight and GST are taken from it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="fleet.order",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="place_of_supply",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reverse_charge",
            field=models.BooleanField(
                default=False, help_text="GST payable by the consignee under RCM"
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="otp_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting", "Awaiting delivery"),
                    ("submitted", "Submitted, awaiting review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="awaiting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="verified_by",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="freight_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="fleet.trip",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="captured_at",
            field=models.DateTimeField(
                blank=True, help_text="When the driver submitted it", null=True
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="file_url",
            field=models.URLField(
                blank=True,
                help_text="Signature image, photo of the signed LR, or scanned POD",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="otp",
            field=models.CharField(
                blank=True,
                help_text="Issued to the consignee, quoted back by the driver",
                max_length=6,
            ),
        ),
        migrations.AddIndex(
            model_name="proofofdelivery",
            index=models.Index(
                fields=["status", "-created_at"], name="fleet_proof_status_0585d2_idx"
            ),
        ),
    ]
