# Generated by Django 4.2.23 on 2026-08-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0005_settle_existing_proofs"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="courier_awb_number",
            field=models.CharField(
                blank=True,
                help_text="The courier's own tracking / AWB number",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="courier_dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="courier_expected_by",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="courier_name",
            field=models.CharField(
                blank=True,
                help_text="e.g. India Post, Blue Dart, DTDC, Professional Couriers",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="courier_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="courier_remarks",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="courier_status",
            field=models.CharField(
                choices=[
                    ("not_sent", "Not sent"),
                    ("dispatched", "Dispatched"),
                    ("in_transit", "In transit"),
                    ("delivered", "Received at office"),
                    ("lost", "Lost in transit"),
                ],
                default="not_sent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="physical_copy_required",
            field=models.BooleanField(
                default=False,
                help_text="A signed physical POD/LR must also come back by courier",
            ),
        ),
        migrations.AddIndex(
            model_name="proofofdelivery",
            index=models.Index(
                fields=["courier_status"], name="fleet_proof_courier_0e589f_idx"
            ),
        ),
    ]
