# Generated by Django 4.2.23 on 2026-08-09 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0006_proofofdelivery_courier_awb_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="contract_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles_here",
                to="fleet.place",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles_now",
                to="fleet.trip",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="expected_available_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner_name",
            field=models.CharField(
                blank=True,
                help_text="Transport owner, when not this fleet's own vendor record",
                max_length=180,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status_since",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this vehicle is attached or outside-sourced",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="fleet.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("own", "Own vehicle"),
                    ("attached", "Attached vehicle"),
                    ("leased", "Leased"),
                    ("outside", "Outside-sourced (vendor hire)"),
                ],
                default="own",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("idle", "Idle"),
                    ("allocated", "Allocated"),
                    ("running", "Running"),
                    ("loaded", "Loaded"),
                    ("unloaded", "Unloaded"),
                    ("under_maintenance", "Under maintenance"),
                    ("driver_unavailable", "Driver unavailable"),
                    ("breakdown", "Breakdown"),
                    ("at_customer_location", "At customer location"),
                    ("awaiting_loading", "Awaiting loading"),
                    ("awaiting_unloading", "Awaiting unloading"),
                    ("inactive", "Inactive"),
                    ("on_trip", "On trip"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VehicleStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("idle", "Idle"),
                            ("allocated", "Allocated"),
                            ("running", "Running"),
                            ("loaded", "Loaded"),
                            ("unloaded", "Unloaded"),
                            ("under_maintenance", "Under maintenance"),
                            ("driver_unavailable", "Driver unavailable"),
                            ("breakdown", "Breakdown"),
                            ("at_customer_location", "At customer location"),
                            ("awaiting_loading", "Awaiting loading"),
                            ("awaiting_unloading", "Awaiting unloading"),
                            ("inactive", "Inactive"),
                            ("on_trip", "On trip"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=240)),
                ("changed_by", models.CharField(blank=True, max_length=150)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_status_events",
                        to="fleet.place",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_status_events",
                        to="fleet.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_log",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-started_at"],
                        name="fleet_vehic_vehicle_c25234_idx",
                    )
                ],
            },
        ),
    ]
