# Generated by Django 4.2.23 on 2026-08-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0008_backfill_ownership_and_trips"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleHire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hire_type",
                    models.CharField(
                        choices=[("contract", "Contract rate"), ("spot", "Spot hire")],
                        default="spot",
                        max_length=10,
                    ),
                ),
                ("outside_vehicle_number", models.CharField(blank=True, max_length=20)),
                ("outside_vehicle_type", models.CharField(blank=True, max_length=60)),
                ("outside_capacity_kg", models.PositiveIntegerField(default=0)),
                ("driver_name", models.CharField(blank=True, max_length=120)),
                ("driver_phone", models.CharField(blank=True, max_length=20)),
                ("driver_licence", models.CharField(blank=True, max_length=40)),
                ("gps_available", models.BooleanField(default=False)),
                (
                    "agreed_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="A total for 'per trip', otherwise a per-unit rate for rate_basis",
                        max_digits=12,
                    ),
                ),
                (
                    "rate_basis",
                    models.CharField(
                        choices=[
                            ("trip", "Per trip"),
                            ("km", "Per km"),
                            ("day", "Per day"),
                            ("ton", "Per ton"),
                            ("other", "Other"),
                        ],
                        default="trip",
                        max_length=10,
                    ),
                ),
                (
                    "loading_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unloading_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "detention_free_hours",
                    models.DecimalField(decimal_places=2, default=24, max_digits=6),
                ),
                (
                    "detention_rate_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "toll_responsibility",
                    models.CharField(
                        choices=[("ours", "Fleet pays"), ("vendor", "Vendor pays")],
                        default="vendor",
                        max_length=10,
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "advance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Agreed penalty for shortage, damage or delay",
                        max_digits=12,
                    ),
                ),
                ("payment_terms_days", models.PositiveIntegerField(default=30)),
                ("remarks", models.CharField(blank=True, max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("billed", "Billed"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hires",
                        to="fleet.order",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hires",
                        to="fleet.trip",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires",
                        to="fleet.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="fleet_vehic_status_3f23ce_idx",
                    )
                ],
            },
        ),
    ]
