# Generated by Django 4.2.23 on 2026-08-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0009_vehiclehire"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="end_odometer_km",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="freight_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Used when this trip has no linked order to price it from",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="google_km",
            field=models.PositiveIntegerField(
                default=0, help_text="Planned distance, e.g. from Google Maps"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="load_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="load_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dry", "Dry"),
                    ("chiller", "Chiller"),
                    ("frozen", "Frozen"),
                    ("empty", "Empty (no cargo)"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="passed_km",
            field=models.PositiveIntegerField(
                default=0, help_text="Distance accepted for costing and billing"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_odometer_km",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="unload_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="advance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Diesel/cash given to the driver up front, settled against actual trip expenses",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="tripexpense",
            name="category",
            field=models.CharField(
                choices=[
                    ("diesel", "Diesel"),
                    ("toll", "Toll / FASTag"),
                    ("cash_toll", "Cash toll"),
                    ("driver_allowance", "Driver bhatta"),
                    ("loading", "Loading"),
                    ("unloading", "Unloading"),
                    ("rto_fine", "RTO fine"),
                    ("police", "Police / checkpost"),
                    ("parking", "Parking"),
                    ("repair", "On-road repair / R&M"),
                    ("permit", "Permit / state border tax"),
                    ("halting", "Halting / waiting charges"),
                    ("way_side", "Way side expense"),
                    ("kata", "Weighbridge / kata"),
                    ("adblue", "AdBlue"),
                    ("salary", "Driver salary (trip share)"),
                    ("other", "Other"),
                ],
                default="toll",
                max_length=24,
            ),
        ),
    ]
