# Generated by Django 4.2.23 on 2026-08-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0010_trip_end_odometer_km_trip_freight_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="average_speed_kph",
            field=models.DecimalField(
                decimal_places=1,
                default=40,
                help_text="Fallback average speed for route timing where no travel-time matrix entry exists",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("container", "Container"),
                    ("tanker", "Tanker"),
                    ("flatbed", "Flatbed"),
                    ("reefer", "Reefer"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="home_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_vehicles",
                to="fleet.place",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="max_drive_hours_per_day",
            field=models.DecimalField(decimal_places=1, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="reefer_fuel_lph",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Reefer unit diesel burn per hour while running, litres",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="reefer_max_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="reefer_min_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="temperature_class",
            field=models.CharField(
                choices=[
                    ("dry", "Dry"),
                    ("chiller", "Chiller"),
                    ("frozen", "Frozen"),
                    ("multi", "Multi-compartment"),
                ],
                default="dry",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="volume_cbm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
