# Generated by Django 4.2.23 on 2026-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0011_vehicle_average_speed_kph_vehicle_body_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indent",
            name="priority",
            field=models.CharField(default="normal", max_length=20),
        ),
        migrations.AddField(
            model_name="indent",
            name="temp_set_point_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="temperature_class",
            field=models.CharField(
                choices=[
                    ("dry", "Dry"),
                    ("chiller", "Chiller"),
                    ("frozen", "Frozen"),
                    ("multi", "Multi-compartment"),
                ],
                default="dry",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="temp_set_point_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="temperature_class",
            field=models.CharField(
                choices=[
                    ("dry", "Dry"),
                    ("chiller", "Chiller"),
                    ("frozen", "Frozen"),
                    ("multi", "Multi-compartment"),
                ],
                default="dry",
                max_length=10,
            ),
        ),
    ]
