# Generated by Django 4.2.23 on 2026-08-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0012_indent_priority_indent_temp_set_point_c_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorLaneRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("origin_city", models.CharField(max_length=80)),
                ("destination_city", models.CharField(max_length=80)),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        help_text="Blank matches any vehicle type",
                        max_length=60,
                    ),
                ),
                (
                    "temperature_class",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("chiller", "Chiller"),
                            ("frozen", "Frozen"),
                            ("multi", "Multi-compartment"),
                        ],
                        default="dry",
                        max_length=10,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "rate_basis",
                    models.CharField(
                        choices=[
                            ("trip", "Per trip"),
                            ("km", "Per km"),
                            ("day", "Per day"),
                            ("ton", "Per ton"),
                            ("other", "Other"),
                        ],
                        default="trip",
                        max_length=10,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("remarks", models.CharField(blank=True, max_length=240)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lane_rates",
                        to="fleet.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["origin_city", "destination_city"],
                "indexes": [
                    models.Index(
                        fields=["origin_city", "destination_city"],
                        name="fleet_vendo_origin__432d16_idx",
                    )
                ],
            },
        ),
    ]
