# Generated by Django 4.2.23 on 2026-08-17

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0013_vendorlanerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="billing_party_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="customer",
            name="pod_preference",
            field=models.CharField(choices=[("epod", "ePOD"), ("physical", "Physical POD"), ("both", "ePOD and physical POD")], default="epod", max_length=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="invoice_delivery_preference",
            field=models.CharField(choices=[("soft_copy", "Soft copy"), ("hard_copy", "Hard copy"), ("both", "Soft and hard copy")], default="soft_copy", max_length=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(choices=[("dry", "Dry"), ("reefer", "Reefer"), ("both", "Dry and reefer")], default="both", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms_days",
            field=models.PositiveSmallIntegerField(choices=[(30, "30 days"), (45, "45 days"), (90, "90 days")], default=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="vendor_vehicle_advance_percent",
            field=models.DecimalField(decimal_places=2, default=Decimal("90"), max_digits=5, validators=[MinValueValidator(0), MaxValueValidator(100)], help_text="Advance payable to a vendor when its vehicle is deployed for this customer"),
        ),
        migrations.AddField(
            model_name="customer",
            name="vendor_vehicle_advance_trigger",
            field=models.CharField(choices=[("after_loading", "After vehicle loading")], default="after_loading", max_length=24),
        ),
    ]
