# Generated by Django 4.2.23 on 2026-08-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_customer_kyc_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='delivery_access',
            field=models.CharField(choices=[('no_entry_area', 'No-entry area'), ('no_restriction', 'Without no-entry restriction')], default='no_restriction', max_length=20),
        ),
        migrations.AddField(
            model_name='indent',
            name='expected_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='expected_running_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='indent',
            name='indent_type',
            field=models.CharField(choices=[('part_load', 'Part load'), ('ftl', 'Full truck load')], default='ftl', max_length=12),
        ),
        migrations.AddField(
            model_name='indent',
            name='temp_max_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='temp_min_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='temp_tolerance_c',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_access',
            field=models.CharField(choices=[('no_entry_area', 'No-entry area'), ('no_restriction', 'Without no-entry restriction')], default='no_restriction', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_running_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='temp_max_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='temp_min_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='temp_tolerance_c',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
    ]
