# Generated by Django 4.2.23 on 2026-08-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0014_backfill_tripexpense_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="line_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="One row per consignment on a consolidated invoice - a snapshot at issue time, the same way a lorry receipt's own fields are",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="orders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Every consignment this bill covers, for a consolidated invoice raised across a trip - see fleet.billing.build_invoice_from_trip",
                related_name="consolidated_invoices",
                to="fleet.order",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="The consignment this bills. Freight and GST are taken from it. Null on a consolidated invoice - see `orders` and `line_items` instead.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="fleet.order",
            ),
        ),
    ]
