# Generated by Django 4.2.23 on 2026-08-20 06:03

from django.db import migrations, models
import django.db.models.deletion


def dedupe_proofs_of_delivery(apps, schema_editor):
    """Before the uniqueness constraint below can be added, any order that
    somehow picked up more than one ProofOfDelivery - the bug this migration
    closes off - needs to be down to one. Keep the verified one if there is
    a verified one, otherwise the most recently created, and drop the rest."""
    from django.db.models import Count

    ProofOfDelivery = apps.get_model("fleet", "ProofOfDelivery")
    duplicated_order_ids = (
        ProofOfDelivery.objects.values("order_id").annotate(n=Count("id")).filter(n__gt=1).values_list("order_id", flat=True)
    )
    for order_id in duplicated_order_ids:
        proofs = list(ProofOfDelivery.objects.filter(order_id=order_id).order_by("-created_at"))
        keeper = next((p for p in proofs if p.status == "verified"), proofs[0])
        for proof in proofs:
            if proof.pk != keeper.pk:
                proof.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0017_invoice_consolidation"),
    ]

    operations = [
        migrations.RunPython(dedupe_proofs_of_delivery, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="order",
            field=models.ForeignKey(
                help_text="One ePOD per consignment - a rejected capture is corrected in place (see ProofOfDeliveryViewSet.reject), not replaced with a second row",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proofs",
                to="fleet.order",
                unique=True,
            ),
        ),
    ]
