# Generated by Django 4.2.23 on 2026-08-20 13:46

from django.db import migrations, models
from django.db.models import Count


def report_cards_affected_by_the_new_default(apps, schema_editor):
    """`fixed_charge_scope` defaults every ServiceRate to "per_trip", the
    correct semantics for a lorry rate card and the fix for
    docs/MULTIPOINT-FREIGHT.md's over-billing defect. It does not touch any
    stored Order.freight_amount - repricing is an explicit act (the
    recalculate-freight endpoint), never a silent side effect of a deploy.

    What it does do is print, once, every rate card that is actually exposed
    to the defect - base_charge, minimum_charge or a per_trip/per_hour rate
    type, used by more than one order on the same trip - so whoever runs this
    deploy can see the blast radius and flip a genuine per-consignment card
    (a parcel/PTL booking fee, say) to fixed_charge_scope="per_consignment"
    before recalculating anything.
    """
    ServiceRate = apps.get_model("fleet", "ServiceRate")
    Order = apps.get_model("fleet", "Order")

    candidates = ServiceRate.objects.filter(
        models.Q(base_charge__gt=0) | models.Q(minimum_charge__gt=0) |
        models.Q(rate_type__in=["per_trip", "per_hour"])
    )
    if not candidates.exists():
        return

    flagged = []
    for rate in candidates:
        multi_order_trips = (
            Order.objects.filter(service_rate=rate, trip__isnull=False)
            .values("trip_id").annotate(n=Count("id")).filter(n__gt=1).count()
        )
        if multi_order_trips:
            flagged.append((rate.code, rate.name, multi_order_trips))

    if flagged:
        print("\nMULTIPOINT-FREIGHT: the following rate cards have carried more than "
              "one order on the same trip and are about to default to "
              "fixed_charge_scope='per_trip'. Their affected orders are NOT repriced "
              "by this migration - review each card, then reprice with "
              "POST /trips/{id}/recalculate-freight/ (docs/MULTIPOINT-FREIGHT.md):")
        for code, name, trip_count in flagged:
            print(f"  - {code} ({name}): {trip_count} trip(s) with more than one order on it")


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0019_vehicle_size_vehicle_type_masters"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="freight_source",
            field=models.CharField(
                choices=[
                    ("rate_card", "Priced from its own rate card"),
                    ("trip_share", "Share of a trip-level freight"),
                    ("mixed", "Own rate card plus a trip share"),
                    ("manual", "Entered by hand"),
                ],
                default="manual",
                help_text="Where freight_amount came from - see fleet.freight.apportion_trip_freight",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servicerate",
            name="fixed_charge_scope",
            field=models.CharField(
                choices=[
                    ("per_trip", "Once per trip"),
                    ("per_consignment", "Once per consignment"),
                ],
                default="per_trip",
                help_text="How base charge, minimum charge, per-hour and halting are levied on a multi-point run carrying several orders: once for the whole trip and divided among them (the right default for a lorry rate card), or once per consignment (for a parcel/PTL card whose base charge is really a per-booking fee). See docs/MULTIPOINT-FREIGHT.md.",
                max_length=20,
            ),
        ),
        migrations.RunPython(report_cards_affected_by_the_new_default, migrations.RunPython.noop),
    ]
