# Generated by Django 4.2.23 on 2026-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("to_address", models.CharField(max_length=240)),
                ("subject", models.CharField(blank=True, max_length=240)),
                ("body", models.TextField(blank=True)),
                ("template_key", models.CharField(blank=True, max_length=60)),
                ("reference_type", models.CharField(blank=True, max_length=40)),
                ("reference_id", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_by", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="iam_outboun_referen_44d2a0_idx",
                    ),
                    models.Index(
                        fields=["status"], name="iam_outboun_status_2ebfb6_idx"
                    ),
                ],
            },
        ),
    ]
