# Generated by Django 4.2.23 on 2026-08-13 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voucher_portal", "0004_portalbatch_artwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalbatch",
            name="first_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portalbatch",
            name="first_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portaluseraccess",
            name="can_view_others_vouchers",
            field=models.BooleanField(
                default=False,
                help_text="Off: this user only sees batches and vouchers they raised themselves. On: they see everything in their departments. Roles that approve or report can always see across users regardless - an approver who could only see their own requests would have nothing to approve.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted for approval"),
                    ("first_approved", "First approval granted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="portalbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending First Approval"),
                    ("pending_second_approval", "Pending Second Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("generating", "Generating"),
                    ("generated", "Generated"),
                    ("partially_issued", "Partially Issued"),
                    ("fully_issued", "Fully Issued"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="portaluseraccess",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="A user can belong to any number of departments. Empty means every department - only meaningful for Administrator or Report Viewer; Requester/Approver with no department sees nothing.",
                related_name="staff",
                to="voucher_portal.department",
            ),
        ),
    ]
