# Generated by Django 4.2.23 on 2026-08-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoucherBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("series_prefix", models.CharField(max_length=40)),
                (
                    "padding",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="Zero-padded width of the numeric part"
                    ),
                ),
                ("start_number", models.PositiveIntegerField()),
                ("end_number", models.PositiveIntegerField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="AED", max_length=8)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Whoever filled in the form - free text, there is no login",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=60, unique=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="AED", max_length=8)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("unassigned", "Unassigned"), ("issued", "Issued")],
                        default="unassigned",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="vouchers.voucherbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="vouchers_gi_status_27776d_idx"
                    ),
                    models.Index(
                        fields=["phone_number"], name="vouchers_gi_phone_n_dc9e53_idx"
                    ),
                ],
            },
        ),
    ]
