# Generated by Django 4.2.23 on 2026-08-08 09:46

from django.db import migrations, models
import voucher_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchertemplate",
            name="field_geometry",
            field=models.JSONField(
                blank=True, default=voucher_portal.models.default_field_geometry
            ),
        ),
    ]
